
# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 50000 # 500000 for corridor and 3s5z_vs_3s6z

runner: "parallel"
# runner: "episode"
batch_size_run: 8
buffer_size: 5000
# batch_size_run: 2
# t_max: 1050000
batch_size: 128

breakpoint: 700000

# update the target network every {} episodes
target_update_interval: 200

# use the Q_Learner to train
mac: "n_mac"
agent: "att_rnn" # self-attention for communication
rnn_hidden_dim: 64
agent_output_type: q
att_heads: 4
att_embed_dim: 32
double_q: True
learner: "qplex_learner_teacher"
mixer: "dmaq_qatten"
mixing_embed_dim: 32
hypernet_embed: 64
adv_hypernet_layers: 2
adv_hypernet_embed: 64
td_lambda: 0.3
lr: 0.001

num_kernel: 4
is_minus_one: True
weighted_head: True
is_adv_attention: True
is_stop_gradient: True

n_head: 4  # attention head number
attend_reg_coef: 0.001
state_bias: True  # the constant value c(s) in the paper
mask_dead: False
weighted_head: False
nonlinear: False
lamb: 0.02
alpha: 1.0
optimizer: 'adam'
grad_norm_clip: 10.0
use_onehot_loss: True
evaluate: False
unit_dim: 7
#save_buffer: True
name: "qplex_cadp"